# @package task
name: G1Flat

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot: 
  name: g1_waist_unlocked
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: 
    .*elbow_joint: 0.5
    .*shoulder.*: 0.5
    .*hip.*: 0.5
    .*knee.*: 0.5
    waist_yaw_joint: 0.25
    waist_roll_joint: 0.25
    waist_pitch_joint: 0.25
    .*ankle.*: 0.25
  max_delay: 1
  alpha: [0.6, 0.8]
  # custom_command:
  #   .*wrist_roll_joint: 0.
  #   .*wrist_pitch_joint: 0.
  #   .*wrist_yaw_joint: 0.

command:
  _target_: active_adaptation.envs.mdp.commands.locomotion.Command2
  linvel_x_range: [-0.8, 1.4]
  linvel_y_range: [-0.8, 0.8]
  angvel_range: [-2.0, 2.0]
  yaw_stiffness_range: [0.5, 1.0]
  use_stiffness_ratio: 0.9
  stand_prob: 0.05

# command:
#   _target_: active_adaptation.envs.mdp.commands.impedance.VelocityImpulse
#   linvel_x_range: [-1.0, 1.6]
#   linvel_y_range: [-0.8, 0.8]
#   angvel_range:   [-2.0, 2.0]
#   yaw_stiffness_range: [0.5, 1.1]
#   use_stiffness_ratio: 0.99
#   aux_input_range: [.5, 1.]
#   resample_prob: 0.5
#   stand_prob: 0.08
#   target_yaw_range: 
#     - [-0.3927,  0.3927]
#     - [ 1.1781,  1.9635]
#     - [ 2.7489,  3.5343]
#     - [ 4.3197,  5.1051]
#   adaptive: false


observation:
  # command:
  policy:
    command:
    root_angvel_b:  {noise_std: 0.05}
    gravity_multistep: {steps: 3, noise_std: 0.05}
    joint_pos_multistep: {steps: 3, noise_std: 0.05}
    joint_vel_multistep: {steps: 3, noise_std: 0.2}
    prev_actions: {steps: 3, permute: true}
  # priv:
    applied_action:   {}
    root_linvel_b:    {}
    # feet_pos_b:       {feet_names: .*ankle_roll_link}
    # feet_vel_b:       {feet_names: .*ankle_roll_link}
    body_height:  {body_names: .*ankle_roll_link}
    applied_torque:   {}

reward:
  loco:
    linvel_exp:         {weight: 1.5, enabled: true, dim: 2, gamma: 0.8}
    linvel_projection:  {weight: 0.5, enabled: true}
    angvel_z_exp:       {weight: 1.2, enabled: true, gamma: 0.8}
    angvel_xy_l2:       {weight: 0.01, enabled: true, body_names: ["pelvis", "torso_link"]}
    linvel_z_l2:        {weight: 0.5, enabled: true}
    tracking_base_height: {weight: 2.0, enabled: true, target_height: 0.74}
    single_foot_contact: {weight: 0.75, enabled: true, body_names: .*ankle_roll_link, margin: 0.2}

    energy_l1:          {weight: 2.0e-4, enabled: true}
    joint_acc_l2:       {weight: 1.0e-7, enabled: true}
    # joint_torques_l2:   {weight: 5.0e-7, enabled: true}
    body_upright:       {weight: 1.0, enabled: true, body_name: "torso_link"}
    survival:           {weight: 1.0, enabled: true}
    action_rate_l2:     {weight: 0.005, enabled: true}
    action_rate2_l2:    {weight: 0.005, enabled: true}
    feet_air_time:      {weight: 2.0, enabled: true, body_names: .*ankle_roll_link, thres: 0.5}
    joint_vel_l2:       {weight: 1.0e-3, enabled: true, joint_names: [.*shoulder.*]}
    joint_deviation_l2: {weight: 0.1, enabled: true, joint_names: [.*shoulder.*, .*hip_roll_joint, .*elbow_joint]}
  debug:
    feet_slip:          {weight: 0.5, enabled: false, body_names: .*ankle_roll_link}
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*ankle_roll_link}

randomization:
  perturb_body_mass:
    (?!(pelvis|torso_link)).*: [0.8, 1.2]
    pelvis: [0.8, 1.2]
  perturb_body_materials:
    body_names: ".*ankle_roll_link"
    static_friction_range: [0.6, 4.0]
    dynamic_friction_range: [0.6, 4.0]
    restitution_range: [0.0, 0.2]
  motor_params_implicit:
    stiffness_range:
      .*: [0.8, 1.1]
    damping_range:
      .*: [0.8, 1.1]
    armature_range:
      .*: [0.0, 0.01]
  reset_joint_states_uniform:
    pos_ranges:
      .*: [-0.1, 0.1]
    rel: true
  # impulse: {}
  # constant_force:
  #   force_range: [50, 50, 15]
  #   offset_range: [0.1, 0.1, 0.1]

termination:
  crash: 
    body_names_expr:
    - "pelvis"
    - "torso_link"
    - ".*_hip_.*_link"
    - ".*shoulder_.*_link"
    - ".*(wrist|elbow).*"
  fall_over: {xy_thres: 0.9}