# @package task
name: G1Force

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot: 
  name: g1_27dof
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: 
    .*elbow_joint: 0.5
    .*shoulder.*: 0.5
    .*hip.*: 0.5
    .*knee.*: 0.5
    waist_yaw_joint: 0.25
    # waist_roll_joint: 0.25
    .*ankle.*: 0.25
  max_delay: 1
  alpha: [0.5, 1.0]
  custom_command:
    .*wrist_roll_joint: 0.
    .*wrist_pitch_joint: 0.
    .*wrist_yaw_joint: 0.

command:
  _target_: active_adaptation.envs.mdp.commands.impedance.Impedance
  body_names: [pelvis, torso_link]
  virtual_mass_range: null # [1.0, 5.0]
  constant_force_scale: [40., 40., 15.]
  constant_force_offset_scale: [0., 0., 0.]
  temporal_smoothing: 32
  linear_kp_range: [4.0, 24.0]
  angular_kp_range: [4.0, 24.0]
  max_acc_xy: [8.0, 8.0]
  max_vel_xy: [1.5, 0.9]

observation:
  command:
    command:
    oscillator_biped: {}
  policy:
    root_angvel_b:  {noise_std: 0.05}
    projected_gravity_b: {noise_std: 0.05}
    joint_pos: {noise_std: 0.05}
    joint_vel: {noise_std: 0.2}
    prev_actions:   {steps: 4}
  priv:
    command_hidden:
    applied_action:   {}
    root_linvel_b:    {}
    feet_pos_b:       {feet_names: .*ankle_roll_link}
    feet_vel_b:       {feet_names: .*ankle_roll_link}
    # feet_height_map:  {feet_names: .*ankle_link }
    applied_torque:   {}
    contact_indicator: {body_names: [.*ankle_roll_link], timing: false}
  flag_:
    is_standing:      {}
  ext:
    external_forces:  {body_names: ["pelvis"]}
    external_torques: {body_names: ["pelvis"]}
  ext_:
    external_forces:  {body_names: ["pelvis"], divide_by_mass: false}
    external_torques: {body_names: ["pelvis"], divide_by_mass: false, scale: 0.2}

reward:
  loco:
    impedance_yaw_pos:      {weight: 0.75, enabled: true}
    impedance_yaw_vel:      {weight: 1.0, enabled: true}
    impedance_pos:      {weight: 0.75, enabled: true}
    impedance_vel:      {weight: 1.5, enabled: true}
    impedance_acc:      {weight: 1.0, enabled: true}
    oscillator_biped:   {weight: 1.0, enabled: true}

    angvel_xy_l2:       {weight: 0.02, enabled: true}
    linvel_z_l2:        {weight: 1.0, enabled: true}

    energy_l1:          {weight: 2.0e-4, enabled: true}
    joint_acc_l2:       {weight: 3.5e-8, enabled: true}
    joint_torques_l2:   {weight: 5.0e-7, enabled: true}
    # stand: 0.5
    body_upright:       {weight: 1.0, enabled: true, body_name: "torso_link"}
    survival:           {weight: 1.0, enabled: true}
    action_rate_l2:     {weight: 0.01, enabled: true}
    action_rate2_l2:    {weight: 0.005, enabled: true}
    feet_air_time:      {weight: 1.0, enabled: true, body_names: .*ankle_roll_link, thres: 0.4}
    feet_slip:          {weight: 0.5, enabled: false, body_names: .*ankle_roll_link}
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*ankle_roll_link}
    joint_deviation_l2: {weight: 0.1, enabled: true, joint_names: [.*shoulder.*, .*hip_roll_joint, .*elbow_joint]}
  metrics:
    impedance_acc_error: {weight: 1.0, enabled: false}
    impedance_pos_error: {weight: 1.0, enabled: false}

randomization:
  perturb_body_mass:
    (?!(pelvis|torso_link)).*: [0.7, 1.1]
    pelvis: [0.7, 1.1]
  perturb_body_materials:
    body_names: ".*ankle_roll_link"
    static_friction_range: [0.6, 4.0]
    dynamic_friction_range: [0.6, 4.0]
    restitution_range: [0.0, 0.2]
  motor_params_implicit:
    stiffness_range:
      .*: [0.8, 1.1]
    damping_range:
      .*: [0.8, 1.1]
    armature_range:
      .*: [0.0, 0.01]
  reset_joint_states_uniform:
    pos_ranges:
      .*: [-0.1, 0.1]
    rel: true

termination:
  crash: 
    body_names_expr:
    - "pelvis"
    - "torso_link"
    - ".*_hip_.*_link"
    - ".*shoulder_.*_link"
    - ".*wrist_.*_link"
  fall_over: {xy_thres: 0.8}