"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cyan_lower_bodyimu_data_lcmt(object):
    __slots__ = ["quat", "gyro", "rpy", "accelerometer", "posEst", "velEst", "contact_state"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "int8_t"]

    __dimensions__ = [[4], [3], [3], [3], [3], [3], [12]]

    def __init__(self):
        self.quat = [ 0.0 for dim0 in range(4) ]
        self.gyro = [ 0.0 for dim0 in range(3) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.accelerometer = [ 0.0 for dim0 in range(3) ]
        self.posEst = [ 0.0 for dim0 in range(3) ]
        self.velEst = [ 0.0 for dim0 in range(3) ]
        self.contact_state = [ 0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(cyan_lower_bodyimu_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack('>3f', *self.accelerometer[:3]))
        buf.write(struct.pack('>3f', *self.posEst[:3]))
        buf.write(struct.pack('>3f', *self.velEst[:3]))
        buf.write(struct.pack('>12b', *self.contact_state[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cyan_lower_bodyimu_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cyan_lower_bodyimu_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cyan_lower_bodyimu_data_lcmt()
        self.quat = struct.unpack('>4f', buf.read(16))
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.accelerometer = struct.unpack('>3f', buf.read(12))
        self.posEst = struct.unpack('>3f', buf.read(12))
        self.velEst = struct.unpack('>3f', buf.read(12))
        self.contact_state = struct.unpack('>12b', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if cyan_lower_bodyimu_data_lcmt in parents: return 0
        tmphash = (0x95d3a72473d29400) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cyan_lower_bodyimu_data_lcmt._packed_fingerprint is None:
            cyan_lower_bodyimu_data_lcmt._packed_fingerprint = struct.pack(">Q", cyan_lower_bodyimu_data_lcmt._get_hash_recursive([]))
        return cyan_lower_bodyimu_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cyan_lower_bodyimu_data_lcmt._get_packed_fingerprint())[0]

