"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cyan_armwaisthead_data_lcmt(object):
    __slots__ = ["q", "qd", "tauIq", "ext_contact", "tauCom"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[18], [18], [18], [12], [18]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(18) ]
        self.qd = [ 0.0 for dim0 in range(18) ]
        self.tauIq = [ 0.0 for dim0 in range(18) ]
        self.ext_contact = [ 0.0 for dim0 in range(12) ]
        self.tauCom = [ 0.0 for dim0 in range(18) ]

    def encode(self):
        buf = BytesIO()
        buf.write(cyan_armwaisthead_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>18f', *self.q[:18]))
        buf.write(struct.pack('>18f', *self.qd[:18]))
        buf.write(struct.pack('>18f', *self.tauIq[:18]))
        buf.write(struct.pack('>12f', *self.ext_contact[:12]))
        buf.write(struct.pack('>18f', *self.tauCom[:18]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cyan_armwaisthead_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cyan_armwaisthead_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cyan_armwaisthead_data_lcmt()
        self.q = struct.unpack('>18f', buf.read(72))
        self.qd = struct.unpack('>18f', buf.read(72))
        self.tauIq = struct.unpack('>18f', buf.read(72))
        self.ext_contact = struct.unpack('>12f', buf.read(48))
        self.tauCom = struct.unpack('>18f', buf.read(72))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if cyan_armwaisthead_data_lcmt in parents: return 0
        tmphash = (0xa15e73c2e3aec558) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cyan_armwaisthead_data_lcmt._packed_fingerprint is None:
            cyan_armwaisthead_data_lcmt._packed_fingerprint = struct.pack(">Q", cyan_armwaisthead_data_lcmt._get_hash_recursive([]))
        return cyan_armwaisthead_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cyan_armwaisthead_data_lcmt._get_packed_fingerprint())[0]

