# @package task
name: A1-Position
task: Manipulation
scene: manipulation

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/Velocity@_here_
  - override action: null
  - _self_

robot: a1-arm
terrain: plane
payload: false
homogeneous: false

# action:
#   _target_: active_adaptation.envs.mdp.action.IKResidual
#   action_scaling:
#     arm_joint[1-6]: 0.5
#   max_delay: 1
#   alpha: 0.8
#   fwd: false

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling:
    arm_joint[1-5]: 0.5
  max_delay: 1
  alpha: 0.5
  clip_joint_targets: 0.2

command:
  _target_: active_adaptation.envs.mdp.EEPosition
  ee_name: 'arm_link6'
  ee_base_name: 'arm_base'
  setpoint_x_range: [0.2, 0.6]
  setpoint_y_range: [-0.2, 0.2]
  setpoint_z_range: [0.3, 0.7]

observation:
  policy:
    command:
    joint_pos:    {joint_names: ["arm_joint[1-5]"], noise_std: 0.05}
    joint_vel:    {joint_names: ["arm_joint[1-5]"], noise_std: 0.2}
    prev_actions: {steps: 3}
  priv:
    applied_action:
    applied_torques:  {actuator_name: arm}
    joint_forces:     {}
    jacobians_b:      {body_names: ["arm_link6"], joint_names: ["arm_joint[1-5]"]}
    body_pos:         {body_names: ["arm_link6"]}
    body_vel:         {body_names: ["arm_link6"]}
    cum_error:        {}
 
reward:
  manip:
    # common loco rewards just for sanity check
    survival:           {weight: 1.0, enabled: true}
    impedance_ee_pos:   {weight: 0.5, enabled: true, ee_name: 'arm_link6', l: 0.25}
    ee_angvel_penalty:  {weight: 1.0e-3, enabled: true, ee_name: 'arm_link6'}
    joint_acc_l2:       {weight: 1.0e-5, enabled: true, joint_names: "arm_joint[1-5]"}
    joint_vel_l2:       {weight: 1.0e-2, enabled: true, joint_names: "arm_joint[1-5]"}

termination:
  # joint_acc_exceeds: {thres: 5000.}
  cum_error: {thres: 0.5, min_steps: 50}

randomization:
  reset_joint_states_uniform:
    pos_ranges:
      arm_joint1: [-1.5, 1.5]
      arm_joint2: [0.0, 1.5]
      arm_joint3: [-1.5, 0.0]
      arm_joint4: [-1.0, 1.0]
      arm_joint5: [-1.0, 1.0]
    rel: true
  perturb_body_mass:
    arm_link[1-6]: [0.8, 1.2]
  motor_params:
    actuator_name: arm
    stiffness_range:  [0.7, 1.3]
    damping_range:    [0.7, 1.3]
    armature_range:   [0.0, 0.02]
    homogeneous: ${task.homogeneous}
