name: CY1FlatEval
task: Humanoid

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/Velocity@_here_
  - _self_

robot: cy1
terrain: plane
payload: false

command:
  _target_: active_adaptation.envs.mdp.Command2
  linvel_x_range: [0., 1.25]
  linvel_y_range: [-0.0, 0.0]
  angvel_range: [-1.0, 1.0]
  yaw_stiffness_range: [0.5, 0.7]
  stand_prob: 0.05

observation:
  policy:
    command:
    # root_quat_w:
    root_angvel_b:  {noise_std: 0.05}
    projected_gravity_b: {noise_std: 0.01}
    joint_pos: {noise_std: 0.05}
    joint_vel: {noise_std: 0.2}
    prev_actions:   {steps: 2}
    # clock:  {frequencies: [1, 2]}
    phase: {cycle_range: [1.0, 1.2]}
  priv:
    joint_acc:
    applied_action:   {}
    root_linvel_b:    {yaw_only: true}
    feet_pos_b:       {feet_names: .*leg_link6, yaw_only: true}
    # body_pos_b:       {body_names: .*leg_link4}
    feet_vel_b:       {feet_names: .*leg_link6, yaw_only: true}
    body_vel:         {body_names: .*arm_link5, yaw_only: true}
    feet_height_map:  {feet_names: .*leg_link6 }
    applied_torques:  {actuator_name: base_legs}
    # contact_indicator: {body_names: [".*leg_link6"], timing: false}
  #   motor_params:     {actuator_name: "base_legs"}
  #   body_materials:   {body_names: ".*ankle_link"}
  #   body_mass:        {body_names: ["torso_link", "pelvis"]}
  #   cum_error:        {}
    rewards:     {}

reward:
  linvel_exp:         {weight: 1.5, enabled: true, dim: 3}
  linacc_z_l2:        {weight: 0.005, enabled: false}
  linvel_projection:  {weight: 1.0, enabled: true}
  angvel_z_exp:       {weight: 1.5, enabled: true, world_frame: true}
  angvel_z_exp_shaped: {weight: 1.0, enabled: false}
  linvel_z_l2:        {weight: 0.5, enabled: true}
  # angvel_xy_l2:       {weight: 0.05, enabled: true}
  energy_l1:          {weight: 2.0e-4, enabled: true}
  joint_acc_l2:       {weight: 1.0e-8, enabled: true}
  joint_torques_l2:   {weight: 5.0e-7, enabled: false}
  # stand: 0.5
  orientation:        {weight: 1.0, enabled: true}
  survival:           {weight: 1.0, enabled: true}
  action_rate_l2:     {weight: 0.01, enabled: true}
  feet_air_time:      {weight: 1.0, enabled: true, body_names: .*leg_link6, thres: 0.5}
  feet_slip:          {weight: 0.5, enabled: true, body_names: .*leg_link6}
  feet_contact_count: {weight: 1.0, enabled: false, body_names: .*leg_link6}
  feet_swing:         {weight: 1.0, enabled: true, feet_names: .*leg_link6}
  feet_orientation:   {weight: 0.5, enabled: true, feet_names: .*leg_link6}
  feet_step:          {weight: 2.0, enabled: true, feet_names: .*leg_link6}
  joint_pos_default:  {weight: 0.25, enabled: true}
  body_orientation:   {weight: 0.5, enabled: true, body_name: waist_yaw_link}
  arm_velocity:       {weight: 0.1, enabled: true, arm_names: .*arm_link5}

randomization:
  push:     {body_names: ["base_link", "waist_yaw_link"]}
  perturb_body_mass:
    .*: [0.8, 1.2]
  perturb_body_materials:
    body_names: ".*leg_link6"
    static_friction_range: [0.4, 2.0]
    dynamic_friction_range: [0.4, 2.0]
    restitution_range: [0.0, 0.2]
  motor_params:
    actuator_name:    base_legs
    stiffness_range:  [0.5, 1.2]
    damping_range:    [0.5, 1.2]
  reset_joint_states_uniform:
    pos_ranges:
      .*: [-0.2, 0.2]
    rel: true
  # stumble:  {body_names: ".*leg_link6", stumble_height: 0.045, friction_range: [0.4, 1.8]}

termination:
  crash: 
    body_names_expr: ["waist_yaw_link"]
