# @package task
name: Go2New
task: Quadruped

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/Velocity@_here_
  - _self_

robot: go2
terrain: plane
payload: false
homogeneous: false

command:
  _target_: active_adaptation.envs.mdp.Command2
  linvel_x_range: [-1.0, 1.4]
  linvel_y_range: [-0.5, 0.5]
  angvel_range: [-1.0, 1.0]
  yaw_stiffness_range: [0.5, 0.6]
  base_height_range: [0.25, 0.35]
  resample_prob: 0.5
  stand_prob: 0.05

observation:
  command:
    command:
  obs:
    root_angvel_b: {noise_std: 0.05}
    projected_gravity_b: {noise_std: 0.05}
    joint_pos:    {noise_std: 0.05}
    joint_vel:    {noise_std: 0.2}
    prev_actions: {steps: 2}
  priv:
    applied_action:
    root_linvel_b:
    feet_pos_b:
    feet_height_map:  {feet_names: .*foot }
    applied_torques:  {actuator_name: base_legs}
    contact_indicator: {body_names: [".*_foot"], timing: true}
    cum_error:
  camera:
    camera: {name: camera}

reward:
  linvel_exp:         {weight: 1.5, enabled: true, dim: 3}
  # angvel_z_exp:       {weight: 0.8, enabled: true}
  # angvel_xy_l2:       {weight: 0.02, enabled: true, clip_range: [-1., 0.]}
  # linvel_z_l2:        {weight: 2.0, enabled: true}
  # base_height_l1:     {weight: 0.5, enabled: true, target_height: 0.3}
  # energy_l1:          {weight: 0.0002, enabled: true}
  # joint_acc_l2:       {weight: 2.5e-7, enabled: true, clip_range: [-1., 0.]}
  # joint_torques_l2:   {weight: 2.0e-4, enabled: true, clip_range: [-1., 0.]}
  # quadruped_stand:    {weight: 0.5}
  # survival:           {weight: 1.0, enabled: true}
  # action_rate_l2:     {weight: 0.01, enabled: true}
  # action_rate2_l2:    {weight: 0.005, enabled: true}
  # feet_air_time:      {weight: 0.4, enabled: true, body_names: .*_foot, thres: 0.4}
  # feet_slip:          {weight: 1.0, enabled: false, body_names: .*_foot}
  # feet_contact_count: {weight: 1.0, enabled: false, body_names: .*_foot}
  # undesired_contact:  {body_names: [.*_calf, .*thigh], weight: 0.25, enabled: true}
  # step_up:            {weight: 2.0, enabled: true}
  # step_up_needed:     {weight: 1.0, enabled: false}

termination:
  crash: {body_names_expr: [Head.*, "base"], t_thres: 1.0, z_thres: 0.}
  cum_error: {thres: 0.9}

randomization:
  # perturb_body_mass:
  #   (?!(payload|base|Head.*)).*: [0.8, 1.2]
  #   base: [0.8, 1.2]
  #   Head.*: [25.0, 250.0]
  # perturb_body_materials:
  #   body_names: ".*_foot"
  #   static_friction_range:  [0.6, 2.0]
  #   dynamic_friction_range: [0.6, 2.0]
  #   restitution_range:      [0.0, 0.2]
  #   homogeneous: true # ${task.homogeneous}
  # motor_params:
  #   actuator_name: base_legs
  #   stiffness_range:  [0.8, 1.2]
  #   damping_range:    [0.8, 1.2]
  #   homogeneous: ${task.homogeneous}
  reset_joint_states_scale:
    pos_scales:
      .*: [0.8, 1.2]

