# @package task
name: Go2Flat

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: go2
# terrain: slopes_boxes
terrain: plane


# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: {.*_joint: 0.5}
  max_delay: 1
  alpha: [0.5, 1.0]

command:
  _target_: active_adaptation.envs.mdp.commands.locomotion.Command2
  linvel_x_range: [-1.0, 1.6]
  linvel_y_range: [-0.8, 0.8]
  angvel_range:   [-2.0, 2.0]
  yaw_stiffness_range: [0.5, 1.1]
  use_stiffness_ratio: 0.99
  aux_input_range: [.5, 1.]
  resample_prob: 0.5
  stand_prob: 0.08
  target_yaw_range: 
    - [-0.3927,  0.3927]
    - [ 1.1781,  1.9635]
    - [ 2.7489,  3.5343]
    - [ 4.3197,  5.1051]

# command:
#   _target_: active_adaptation.envs.mdp.commands.impedance.VelocityImpulse
#   linvel_x_range: [-1.0, 1.6]
#   linvel_y_range: [-0.8, 0.8]
#   angvel_range:   [-2.0, 2.0]
#   yaw_stiffness_range: [0.5, 1.1]
#   use_stiffness_ratio: 0.99
#   aux_input_range: [.5, 1.]
#   resample_prob: 0.5
#   stand_prob: 0.08
#   target_yaw_range: 
#     - [-0.3927,  0.3927]
#     - [ 1.1781,  1.9635]
#     - [ 2.7489,  3.5343]
#     - [ 4.3197,  5.1051]
#   adaptive: false

observation:
  command: # won't be normalized
    command:
  policy:
    gravity_multistep: {steps: 3, noise_std: 0.05}
    joint_pos_multistep: {steps: 3, noise_std: 0.05}
    joint_vel_multistep: {steps: 3, noise_std: 0.2}
    prev_actions: {steps: 1, permute: true}
  priv:
    applied_action:
    root_linvel_b:    {yaw_only: true}
    root_angvel_b:
    body_height:      {body_names: .*_foot}
    applied_torque:   {}
    contact_indicator:  {body_names: [".*_foot", ".*_calf"], timing: false}
  ext:
    external_forces:  {body_names: ["base"]}
    external_torques: {body_names: ["base"]}
  aux_target_:
    root_linvel_b:
    root_angvel_b:
    # rewards: {}

reward:
  loco:
    linvel_exp:         {weight: 1.5, enabled: true, dim: 3, yaw_only: true}
    angvel_z_exp:       {weight: 0.8, enabled: true}
    # quadruped_stand:    {weight: 0.5, enabled: true}
  # reg:
    angvel_xy_l2:       {weight: 0.02, enabled: true}
    linvel_z_l2:        {weight: 2.0, enabled: true}
    base_height_l1:     {weight: 2.0, enabled: true, target_height: 0.35}
    energy_l1:          {weight: 0.0002, enabled: true}
    joint_acc_l2:       {weight: 2.5e-7, enabled: true}
    joint_torques_l2:   {weight: 2.0e-4, enabled: true}
    survival:           {weight: 1.0, enabled: true}
    action_rate_l2:     {weight: 0.01, enabled: true}
    action_rate2_l2:    {weight: 0.002, enabled: true}
    feet_air_time:      {weight: 0.2, enabled: true, body_names: .*_foot, thres: 0.4}
    undesired_contact:  {body_names: [.*_calf, .*thigh, Head.*], weight: 0.25, enabled: true}
    support_polygon:    {weight: 4.0, enabled: true, margin: 0.1}
  debug:
    linvel_projection:  {weight: 0.5, enabled: false, yaw_only: true}
    feet_slip:          {weight: 1.0, enabled: false, body_names: .*_foot}
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*_foot}
    feet_swing_height:  {weight: 0.1, enabled: false, target_height: 0.1}

termination:
  crash: {body_names_expr: [Head.*, base], t_thres: 0.06}
  fall_over: {xy_thres: 0.9}
  soft_contact: {body_names: [Head.*, .*_calf]}

randomization:
  # random_scale: [1.0, 1.2]
  perturb_body_mass:
    (?!(payload|base|Head.*)).*: [0.8, 1.2]
    base: [0.8, 1.4]
    # Head.*: [25.0, 250.0]
  rand_body_materials:
    static_friction_range:  {".*_foot": [0.5, 4.0]}
    dynamic_friction_range: {".*_foot": [0.5, 4.0]}
    restitution_range:      {".*_foot": [0.0, 0.5]}
  motor_params:
    actuator_name: base_legs
    stiffness_range:  
      F[L,R]_hip_joint:   [0.8, 1.2]
      F[L,R]_thigh_joint: [0.8, 1.2]
      F[L,R]_calf_joint:  [0.8, 1.2]
      R[L,R]_hip_joint:   [0.8, 1.2]
      R[L,R]_thigh_joint: [0.8, 1.2]
      R[L,R]_calf_joint:  [0.8, 1.2]
    damping_range:
      F[L,R]_hip_joint:   [0.8, 1.2]
      F[L,R]_thigh_joint: [0.8, 1.2]
      F[L,R]_calf_joint:  [0.8, 1.2]
      R[L,R]_hip_joint:   [0.8, 1.2]
      R[L,R]_thigh_joint: [0.8, 1.2]
      R[L,R]_calf_joint:  [0.8, 1.2]
    scale_factor_range:
      .*_hip_joint:   [0.8, 1.2]
      .*_thigh_joint: [0.8, 1.2]
      .*_calf_joint:  [0.8, 1.2]
    armature_range:
      .*: [0.0, 0.02]
  reset_joint_states_scale:
    pos_scales:
      .*: [0.8, 1.2]
  random_joint_offset:
    .*hip_joint: [-0.05, 0.05]
    F[L,R]_thigh_joint: [-0.05, 0.05]
    R[L,R]_thigh_joint: [-0.05, 0.05]
    .*calf_joint: [-0.05, 0.05]
  # impulse: {}
  constant_force:
    force_range: [50, 50, 15]
    offset_range: [0.1, 0.1, 0.1]