/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class cyan_hand_data_lcmt implements lcm.lcm.LCMEncodable
{
    public float q[];
    public float qd[];
    public float tauIq[];
    public float ext_contact[];
 
    public cyan_hand_data_lcmt()
    {
        q = new float[12];
        qd = new float[12];
        tauIq = new float[12];
        ext_contact = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x058e978224580311L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.cyan_hand_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.cyan_hand_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.tauIq[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.ext_contact[a]); 
        }
 
    }
 
    public cyan_hand_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public cyan_hand_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.cyan_hand_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.cyan_hand_data_lcmt o = new lcmtypes.cyan_hand_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q[a] = ins.readFloat();
        }
 
        this.qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qd[a] = ins.readFloat();
        }
 
        this.tauIq = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tauIq[a] = ins.readFloat();
        }
 
        this.ext_contact = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.ext_contact[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.cyan_hand_data_lcmt copy()
    {
        lcmtypes.cyan_hand_data_lcmt outobj = new lcmtypes.cyan_hand_data_lcmt();
        outobj.q = new float[(int) 12];
        System.arraycopy(this.q, 0, outobj.q, 0, 12); 
        outobj.qd = new float[(int) 12];
        System.arraycopy(this.qd, 0, outobj.qd, 0, 12); 
        outobj.tauIq = new float[(int) 12];
        System.arraycopy(this.tauIq, 0, outobj.tauIq, 0, 12); 
        outobj.ext_contact = new float[(int) 12];
        System.arraycopy(this.ext_contact, 0, outobj.ext_contact, 0, 12); 
        return outobj;
    }
 
}

