/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class cyan_lower_bodyimu_data_lcmt implements lcm.lcm.LCMEncodable
{
    public float quat[];
    public float gyro[];
    public float rpy[];
    public float accelerometer[];
    public float posEst[];
    public float velEst[];
    public byte contact_state[];
 
    public cyan_lower_bodyimu_data_lcmt()
    {
        quat = new float[4];
        gyro = new float[3];
        rpy = new float[3];
        accelerometer = new float[3];
        posEst = new float[3];
        velEst = new float[3];
        contact_state = new byte[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x95d3a72473d29400L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.cyan_lower_bodyimu_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.cyan_lower_bodyimu_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quat[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.gyro[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accelerometer[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.posEst[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.velEst[a]); 
        }
 
        outs.write(this.contact_state, 0, 12);
 
    }
 
    public cyan_lower_bodyimu_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public cyan_lower_bodyimu_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.cyan_lower_bodyimu_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.cyan_lower_bodyimu_data_lcmt o = new lcmtypes.cyan_lower_bodyimu_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.quat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readFloat();
        }
 
        this.gyro = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyro[a] = ins.readFloat();
        }
 
        this.rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.accelerometer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accelerometer[a] = ins.readFloat();
        }
 
        this.posEst = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.posEst[a] = ins.readFloat();
        }
 
        this.velEst = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.velEst[a] = ins.readFloat();
        }
 
        this.contact_state = new byte[(int) 12];
        ins.readFully(this.contact_state, 0, (int) 12); 
    }
 
    public lcmtypes.cyan_lower_bodyimu_data_lcmt copy()
    {
        lcmtypes.cyan_lower_bodyimu_data_lcmt outobj = new lcmtypes.cyan_lower_bodyimu_data_lcmt();
        outobj.quat = new float[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        outobj.gyro = new float[(int) 3];
        System.arraycopy(this.gyro, 0, outobj.gyro, 0, 3); 
        outobj.rpy = new float[(int) 3];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 3); 
        outobj.accelerometer = new float[(int) 3];
        System.arraycopy(this.accelerometer, 0, outobj.accelerometer, 0, 3); 
        outobj.posEst = new float[(int) 3];
        System.arraycopy(this.posEst, 0, outobj.posEst, 0, 3); 
        outobj.velEst = new float[(int) 3];
        System.arraycopy(this.velEst, 0, outobj.velEst, 0, 3); 
        outobj.contact_state = new byte[(int) 12];
        System.arraycopy(this.contact_state, 0, outobj.contact_state, 0, 12); 
        return outobj;
    }
 
}

